name: Testing and deployment pipeline

on:
  push:
    branches:
      - master
      - test-branch

jobs:
  pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install backend dependencies
        run: cd backend && npm install
      - name: lint backend
        run: cd backend && npm run lint
      - name: unit test backend
        run: cd backend && npm test
        env:
          TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
          LOGIN_TOKEN_HMAC_KEY: ${{ secrets.LOGIN_TOKEN_HMAC_KEY }}
      - name: install frontend dependencies
        run: cd frontend && npm install
      - name: lint frontend
        run: cd frontend && npm run lint
      - name: unit test frontend
        run: cd frontend && npm test
      - name: build a production version of frontend
        run: cd frontend && npm run build
      - name: run end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          start: npm --prefix backend run start:test
          install: false
          command: npm --prefix frontend run cypress:run
          wait-on: http://localhost:3003
        env:
          TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
          LOGIN_TOKEN_HMAC_KEY: ${{ secrets.LOGIN_TOKEN_HMAC_KEY }}
      - name: bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: frozen-ridge-63934
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: backend
